### ISSUE TITLE
Reproducing get_rscape_powers.sh

### ISSUE THREAD

**Issue by ruthkr** [DasLab/SARSCoV2_Secstruct_Cons#2]
Hello,

This is really great work. 

### Background:
I am trying to follow your steps to get conserved RNA structure on plant viruses, especially using R-scape. 
Recently, I tried to reproduce the bash script `get_rscape_powers.sh` using your [windowed alignment files](https://github.com/DasLab/SARSCoV2_Secstruct_Cons/tree/master/rscape/windows) . However, I did not get the same alignment power results as you have in [`alignment_powers.dat`](https://github.com/DasLab/SARSCoV2_Secstruct_Cons/blob/master/rscape/alignment_powers.dat).

### Results:
- [alignment_powers_macOS.txt](https://github.com/DasLab/SARSCoV2_Secstruct_Cons/files/5575160/alignment_powers_macOS.txt), run on macOS Catalina version 10.15.7 (19H15). 
- [alignment_powers_linux.txt](https://github.com/DasLab/SARSCoV2_Secstruct_Cons/files/5575161/alignment_powers_linux.txt), run on Arch Linux 64-bit (Linux version 5.9.8-arch1-1).

These results are identical (a quick run of `diff` will show that).

### Question:
What version of `R-scape` did you use in this project? Is there any particular thing you did before running `get_rscape_powers.sh`?

I ran the script in R-scape version v1.5.16, in both macOS and GNU/Linux, and they don't match the results on your GitHub. 

Thank you very much.

**Comment by ramyarangan** [comment]
Hi, thank you for reaching out! I am glad that you are using this script.  

I am running with `R-scape` version v1.4.0, which may explain the discrepancy. I just tried pulling the directory from scratch and running the script again with `R-scape` version v1.4.0, and I'm getting the results currently uploaded on Github. I didn't run anything else prior to that script. I've just added a note pointing to this version in the README!

**Comment by ruthkr** [comment]
Hello, thank you very much for your reply. 
Your pipeline is great and easy to follow. Thank you for this. 

I changed the version of my R-scape to v1.4.0, and it worked as expected (it has the same results as [alignment_powers.dat](https://github.com/DasLab/SARSCoV2_Secstruct_Cons/blob/master/rscape/alignment_powers.dat)). 

I agree, it would be great if you add the version of tools you used in README. 😃
